FROM node:lts AS runtime
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm i

ENV HOST=0.0.0.0
ENV PORT=3000

ARG PUBLIC_EMAILJS_SERVICE_ID
ENV PUBLIC_EMAILJS_SERVICE_ID ${PUBLIC_EMAILJS_SERVICE_ID}

ARG PUBLIC_EMAILJS_TEMPLATE_ID
ENV PUBLIC_EMAILJS_TEMPLATE_ID ${PUBLIC_EMAILJS_TEMPLATE_ID}

ARG PUBLIC_EMAILJS_PUBLIC_KEY
ENV PUBLIC_EMAILJS_PUBLIC_KEY ${PUBLIC_EMAILJS_PUBLIC_KEY}

COPY . .
RUN pnpm run build

EXPOSE 3000
CMD node ./dist/server/entry.mjs